from selenium import webdriver

browser = webdriver.Firefox()

def quiz():
    print("Here is a quiz to test your knowledge of farming...")
    print()
    print()
    print("Question 1")
    print("What percentage of the land is used for farming?")
    print()
    print("a. 25%")
    print("b. 50%")
    print("c. 75%")
    answer = input("Make your choice: ")
    if answer == "c":
        print("Correct!")
    print("Here is a quiz to test your general knowledge:")
    print()
    print()
    print("Question 1")
    print("For the longest time people thought the sky was infinite")
    print()
    print("a. True")
    print("b. False")
    answer = input("Make your choice: ")
    if answer == "a":
        print("Correct!")
    print("Question 2")
    print("What color is the sky")
    print()
    print("a. yellow")
    print("b. blue")
    print("c. red")
    answer = input("Make your choice: ")
    if answer == "b":
        print("Correct!")
    print("Question 3")
    print("What percentage of the human is made of water")
    print()
    print("a. 85%")
    print("b. 80%")
    print("c. 75%")
    answer = input("Make your choice: ")
    if answer == "b":
        print("Correct!")
    print("Question 4")
    print("The sky is made entirely of the atomsphere.")
    print()
    print("a. True")
    print("b. False")
    answer = input("Make your choice: ")
    if answer == "a":
        print("Correct!")
    print("Question 5")
    print("How many planets are in the solar system?")
    print()
    print("a. 10")
    print("b. 8")
    print("c. 9")
    answer = input("Make your choice: ")
    if answer == "c":
        print("Correct!")
    print("Question 6")
    print("We live in the milky way galaxy")
    print()
    print("a. True")
    print("b. False")
    answer = input("Make your choice: ")
    if answer == "a":
        print("Correct!")
    print("Question 7")
    print("How many planets are covered in ice?")
    print()
    print("a. 3")
    print("b. 4")
    print("c. 5")
    answer = input("Make your choice: ")
    if answer == "b":
        print("Correct!")
    print("Question 8")
    print("How big is the universe?")
    print()
    print("a. infinite")
    print("b. growing")
    print("c. strinking")
    answer = input("Make your choice: ")
    if answer == "a":
        print("Correct!")
    print("Question 9")
    print("Most food comes from water")
    print()
    print("a. True")
    print("b. False")
    answer = input("Make your choice: ")
    if answer == "b":
        print("Correct!")
    print("Question 10")
    print("What is bigger?")
    print()
    print("a. Pluto")
    print("b. Sky")
    print("c. Venus")
    answer = input("Make your choice: ")
    if answer == "b":
        print("Correct!")